[tool.black]
# Black configuration for consistent formatting
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.cache
  | \.venv
  | venv
  | env
  | build
  | build-ninja
  | __pycache__
  | vcpkg_installed
)/
'''

[tool.isort]
# Import sorting configuration
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# Organize imports for this project
known_first_party = ["agent_control_pkg"]
known_third_party = ["numpy", "pandas", "matplotlib", "yaml", "pathlib"]

[tool.pylint]
# Pylint configuration for academic/research code
max-line-length = 88
disable = [
    "C0103",  # Invalid name (allow single-letter variables for math)
    "R0903",  # Too few public methods
    "R0913",  # Too many arguments (common in scientific functions)
    "W0718",  # Broad exception catching (acceptable for research)
    "C0114",  # Missing module docstring
    "C0115",  # Missing class docstring  
    "C0116",  # Missing function docstring
    "R0914",  # Too many local variables (common in analysis)
    "R0915",  # Too many statements (common in simulation code)
    "C0304",  # Missing final newline (auto-fixed by formatters)
    "W0613",  # Unused argument (common in research callbacks)
    "R0912",  # Too many branches (common in configuration logic)
    "C0301",  # Line too long (handled by black/flake8)
]

[tool.pylint.SIMILARITIES]
# Allow similar code blocks in research/analysis scripts
min-similarity-lines = 10
ignore-comments = true
ignore-docstrings = true

[tool.mypy]
# Type checking configuration (optional for research code)
python_version = "3.8"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

# Exclude build and cache directories
exclude = [
    "build/",
    "build-ninja/", 
    "__pycache__/",
    ".cache/",
    "vcpkg_installed/"
] 