simulation_settings:
  dt: 0.05
  total_time: 120.0
  num_drones: 3
  ziegler_nichols_tuning:
    enable: false
    kp_test_value: 2.5
    enable_auto_search: false
    
    # Expanded search range for improved systems
    auto_search_kp_start: 10.0      # Start higher due to improved stability
    auto_search_kp_step: 5.0        # Larger steps for faster search
    auto_search_kp_max: 200.0       # Much higher max due to anti-windup protection
    simulation_time: 20.0           # Longer simulation for better analysis
    
    # Formation-specific ZN methods
    formation_aware_tuning: true    # Use formation-specific criteria
    formation_stability_margin: 1.5 # Safety factor for formation control
    
    # Quick method testing with proven values
    quick_method_test: 'Off'        # Options: Classic, Conservative, LessOvershoot, NoOvershoot, Aggressive, ModernZN, FormationOptimal
    manual_ku: 150.0                # Updated based on improved system stability
    manual_pu: 12.0                 # Adjusted for realistic oscillation period
csv_enabled: true
metrics_enabled: true
output_directory: output
csv_prefix: sim_data
metrics_prefix: metrics_report
controller_settings:
  pid:
    kp: 7.0
    ki: 1.0
    kd: 4.5
    
    # Axis-specific output limits (m/s²)
    output_min_x: -10.0    # X-axis acceleration limits
    output_max_x: 10.0
    output_min_y: -8.0     # Y-axis often different due to gravity compensation
    output_max_y: 12.0
    
    # Backward compatibility
    output_min: -10.0      # Fallback for single-axis systems
    output_max: 10.0
    
    # Derivative filtering (reduces noise in D-term)
    enable_derivative_filter: true
    derivative_filter_alpha: 0.1    # Low-pass filter coefficient (0.05-0.2 typical)
    
    # Feed-forward control (improves tracking performance)
    enable_feedforward: true       # Testing feed-forward improvements
    velocity_feedforward_gain: 0.8  # Velocity feed-forward coefficient
    acceleration_feedforward_gain: 0.1  # Acceleration feed-forward coefficient
  fls:
    enable: true
    params_file: fuzzy_params.yaml
scenario_settings:
  enable_wind: true
  formation_side_length: 4.0
  formation:
    initial_positions:
      drone_0:
      - 0.0
      - 1.15
      drone_1:
      - -2.0
      - -2.0
      drone_2:
      - 2.0
      - -2.0
  phases:
  - center:
    - 5.0
    - 5.0
    start_time: 0.0
  - center:
    - -5.0
    - 0.0
    start_time: 30.0
  - center:
    - 0.0
    - -5.0
    start_time: 60.0
  - center:
    - 5.0
    - 0.0
    start_time: 90.0
  wind:
    phases:
    - phase: 1
      time_windows:
      - start_time: 5.0
        end_time: 15.0
        force:
        - 3.0
        - 0.0
        is_sine_wave: false
      - start_time: 10.0
        end_time: 20.0
        force:
        - 0.0
        - -1.0
        is_sine_wave: false
    - phase: 2
      time_windows:
      - start_time: 5.0
        end_time: 15.0
        force:
        - -2.0
        - 0.0
        is_sine_wave: false
      - start_time: 10.0
        end_time: 20.0
        force:
        - 0.0
        - 1.5
        is_sine_wave: false
    - phase: 3
      time_windows:
      - start_time: 5.0
        end_time: 10.0
        force:
        - 2.0
        - 0.0
        is_sine_wave: true
        sine_frequency_rad_s: 1.57
      - start_time: 10.0
        end_time: 12.0
        force:
        - 0.0
        - 4.0
        is_sine_wave: false
      - start_time: 12.0
        end_time: 15.0
        force:
        - 0.0
        - -2.0
        is_sine_wave: false
    - phase: 4
      time_windows:
      - start_time: 5.0
        end_time: 15.0
        force:
        - 2.5
        - -2.5
        is_sine_wave: false
output_settings:
  output_directory: simulation_outputs
  csv_enabled: true
  csv_prefix: multi_agent_sim
  metrics_enabled: true
  metrics_prefix: metrics_sim
  console_output:
    enabled: true
    update_interval: 5.0
